"""
Genesis Database — Planning Models

Covers the implementation planning layer:
    implementation_plan     — versioned plan document for a project
    implementation_task     — individual task within a plan
    task_dependency         — dependency edges between tasks

These models represent the output of the PlannerAgent and form the
execution graph consumed by the OrchestratorService.

See docs/BACKEND_SCHEMA.md §12–14 for schema specification.
"""

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import func
from sqlmodel import JSON, Column, DateTime, Field, SQLModel


def _utcnow() -> datetime:
    return datetime.now(UTC)


# =============================================================================
# Enumerations
# =============================================================================


class PlanStatus(StrEnum):
    DRAFT = "draft"
    APPROVED = "approved"
    ACTIVE = "active"
    SUPERSEDED = "superseded"
    ARCHIVED = "archived"


class TaskStatus(StrEnum):
    PENDING = "pending"
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    BLOCKED = "blocked"
    SKIPPED = "skipped"


class TaskType(StrEnum):
    REQUIREMENT = "requirement"
    DESIGN = "design"
    ARCHITECTURE = "architecture"
    DATABASE = "database"
    BACKEND = "backend"
    FRONTEND = "frontend"
    TEST = "test"
    DOCUMENTATION = "documentation"
    VALIDATION = "validation"
    DEPLOYMENT = "deployment"


class DependencyType(StrEnum):
    FINISH_TO_START = "finish_to_start"  # Standard: B starts after A finishes
    SOFT = "soft"  # B should run after A but can run concurrently if needed


# =============================================================================
# Implementation Plan
# =============================================================================


class ImplementationPlan(SQLModel, table=True):
    """
    Versioned implementation plan for a project.

    Generated by the PlannerAgent from technical requirements and backend schema.
    Each planning cycle creates a new version. Only one plan has status=ACTIVE.

    plan_data stores the structured task graph as JSON:
    {
        "phases": [...],
        "tasks": [...],
        "dependencies": [...]
    }
    """

    __tablename__ = "implementation_plan"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(
        foreign_key="project.id",
        index=True,
    )
    version: int = Field(description="Monotonically increasing version number")
    status: str = Field(
        default=PlanStatus.DRAFT,
        max_length=30,
    )
    plan_data: dict = Field(
        sa_column=Column(JSON, nullable=False),
        description="Structured plan as JSON (phases, tasks, dependency graph)",
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


# =============================================================================
# Implementation Task
# =============================================================================


class ImplementationTask(SQLModel, table=True):
    """
    Individual task within an implementation plan.

    Each task is assigned to an agent type and may be parallelized if
    it has no unresolved dependencies.

    The orchestrator reads `parallelizable` and the task dependency graph
    to determine execution order.
    """

    __tablename__ = "implementation_task"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(
        foreign_key="project.id",
        index=True,
    )
    plan_id: uuid.UUID | None = Field(
        default=None,
        foreign_key="implementation_plan.id",
        index=True,
    )
    task_key: str = Field(
        max_length=100,
        description="Stable key unique within the project (e.g., TASK-001)",
    )
    title: str = Field(max_length=500)
    description: str = Field()
    task_type: str = Field(
        default=TaskType.BACKEND,
        max_length=50,
        description="Determines which agent handles this task",
    )
    status: str = Field(
        default=TaskStatus.PENDING,
        max_length=30,
        index=True,
    )
    priority: str | None = Field(default=None, max_length=20)
    agent_type: str | None = Field(
        default=None,
        max_length=50,
        description="Agent type responsible for this task",
    )
    agent_run_id: uuid.UUID | None = Field(
        default=None,
        description="ai_run.id for the current/last agent execution",
    )
    parallelizable: bool = Field(
        default=False,
        description="If True, this task may run concurrently with other parallelizable tasks",
    )
    retry_count: int = Field(
        default=0,
        description="Number of retry attempts so far",
    )
    context: dict | None = Field(
        default=None,
        sa_column=Column(JSON),
        description="Task-specific context for the assigned agent",
    )
    output: dict | None = Field(
        default=None,
        sa_column=Column(JSON),
        description="Structured output from the agent on completion",
    )
    error_message: str | None = Field(
        default=None,
        max_length=2000,
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )
    started_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )
    completed_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True),
    )


# =============================================================================
# Task Dependency
# =============================================================================


class TaskDependency(SQLModel, table=True):
    """
    Directed dependency edge between two implementation tasks.

    task_id depends on depends_on_task_id — meaning depends_on_task_id
    must reach status=COMPLETED before task_id can start.

    Composite primary key: (task_id, depends_on_task_id)
    """

    __tablename__ = "task_dependency"

    task_id: uuid.UUID = Field(
        foreign_key="implementation_task.id",
        primary_key=True,
        index=True,
    )
    depends_on_task_id: uuid.UUID = Field(
        foreign_key="implementation_task.id",
        primary_key=True,
        index=True,
    )
    dependency_type: str = Field(
        default=DependencyType.FINISH_TO_START,
        max_length=30,
    )
