"""
Genesis Database — Project Domain Models

Covers the core project lifecycle entities:
    conversation            — AI conversation associated with a project
    conversation_message    — individual messages within a conversation
    requirement             — structured requirement extracted from conversation
    feature                 — feature derived from requirements
    use_case                — actor-level use case for a feature
    screen                  — UI screen / route
    technical_requirement   — technical-level requirement (infra, performance, security)

All tables include:
    - UUID primary keys
    - Timezone-aware timestamps
    - onupdate=func.now() for updated_at
    - Indexed foreign keys

See docs/BACKEND_SCHEMA.md §5–11 for schema specification.
"""

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import func
from sqlmodel import JSON, Column, DateTime, Field, SQLModel


def _utcnow() -> datetime:
    return datetime.now(UTC)


# =============================================================================
# Enumerations
# =============================================================================


class ConversationStatus(StrEnum):
    ACTIVE = "active"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class MessageRole(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    AGENT = "agent"


class MessageType(StrEnum):
    CHAT = "chat"
    QUESTION = "question"
    REQUIREMENT_SUMMARY = "requirement_summary"
    CONFIRMATION = "confirmation"
    APPROVAL_REQUEST = "approval_request"
    AGENT_STATUS = "agent_status"
    ERROR = "error"
    PROGRESS = "progress"


class RequirementCategory(StrEnum):
    FUNCTIONAL = "functional"
    NON_FUNCTIONAL = "non_functional"
    SECURITY = "security"
    PERFORMANCE = "performance"
    UX = "ux"
    TECHNICAL = "technical"
    CONSTRAINT = "constraint"


class RequirementPriority(StrEnum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class RequirementStatus(StrEnum):
    DRAFT = "draft"
    CONFIRMED = "confirmed"
    IMPLEMENTING = "implementing"
    IMPLEMENTED = "implemented"
    REJECTED = "rejected"


class FeatureStatus(StrEnum):
    PROPOSED = "proposed"
    APPROVED = "approved"
    IMPLEMENTING = "implementing"
    COMPLETE = "complete"
    DEFERRED = "deferred"


class ScreenStatus(StrEnum):
    PLANNED = "planned"
    DESIGNING = "designing"
    DESIGNED = "designed"
    IMPLEMENTING = "implementing"
    COMPLETE = "complete"


# =============================================================================
# Conversation
# =============================================================================


class Conversation(SQLModel, table=True):
    """
    AI conversation tied to a project.

    A project may have multiple conversations (e.g., initial requirement discovery,
    a subsequent change request, a repair discussion). Only one is typically active
    at a time.
    """

    __tablename__ = "conversation"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(
        foreign_key="project.id",
        index=True,
        description="Project this conversation belongs to",
    )
    status: str = Field(
        default=ConversationStatus.ACTIVE,
        max_length=30,
        description="active | completed | abandoned",
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )


# =============================================================================
# Conversation Message
# =============================================================================


class ConversationMessage(SQLModel, table=True):
    """
    Individual message within a conversation.

    Roles:
        user      — message sent by the human user
        assistant — message generated by the AI / LLM
        system    — platform-generated status message
        agent     — message from a specialized AI agent
    """

    __tablename__ = "conversation_message"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    conversation_id: uuid.UUID = Field(
        foreign_key="conversation.id",
        index=True,
    )
    role: str = Field(
        max_length=20,
        description="user | assistant | system | agent",
    )
    content: str = Field(description="Full message content")
    message_type: str = Field(
        default=MessageType.CHAT,
        max_length=50,
        description="Semantic type of this message",
    )
    message_metadata: dict | None = Field(
        default=None,
        sa_column=Column(JSON),
        description="Additional structured data (e.g., requirement IDs, approval state)",
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


# =============================================================================
# Requirement
# =============================================================================


class Requirement(SQLModel, table=True):
    """
    Structured requirement extracted from the user conversation.

    Extracted by the RequirementAgent from ConversationMessages.
    Linked back to the source message via source_message_id.
    """

    __tablename__ = "requirement"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(foreign_key="project.id", index=True)
    requirement_key: str = Field(
        max_length=100,
        description="Stable key unique within the project (e.g., REQ-001)",
    )
    title: str = Field(max_length=500)
    description: str = Field()
    category: str = Field(
        default=RequirementCategory.FUNCTIONAL,
        max_length=50,
    )
    priority: str = Field(
        default=RequirementPriority.MEDIUM,
        max_length=20,
    )
    status: str = Field(
        default=RequirementStatus.DRAFT,
        max_length=30,
    )
    confidence: float | None = Field(
        default=None,
        description="AI confidence score 0.0–1.0 for this requirement extraction",
        ge=0.0,
        le=1.0,
    )
    source_message_id: uuid.UUID | None = Field(
        default=None,
        description="ConversationMessage this requirement was extracted from",
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )


# =============================================================================
# Feature
# =============================================================================


class Feature(SQLModel, table=True):
    """
    A product feature derived from one or more requirements.

    Features are the bridge between user requirements and technical implementation.
    """

    __tablename__ = "feature"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(foreign_key="project.id", index=True)
    feature_key: str = Field(
        max_length=100,
        description="Stable key unique within the project (e.g., FEAT-001)",
    )
    name: str = Field(max_length=500)
    description: str | None = Field(default=None)
    status: str = Field(
        default=FeatureStatus.PROPOSED,
        max_length=30,
    )
    priority: str | None = Field(default=None, max_length=20)
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )


# =============================================================================
# Use Case
# =============================================================================


class UseCase(SQLModel, table=True):
    """
    Actor-level use case for a feature.

    Defines what a specific actor can do in the system.
    """

    __tablename__ = "use_case"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(foreign_key="project.id", index=True)
    use_case_key: str = Field(max_length=100)
    name: str = Field(max_length=500)
    actor: str = Field(max_length=255, description="Who performs this use case")
    description: str = Field()
    preconditions: list | None = Field(default=None, sa_column=Column(JSON))
    postconditions: list | None = Field(default=None, sa_column=Column(JSON))
    status: str = Field(default="draft", max_length=30)
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )


# =============================================================================
# Screen
# =============================================================================


class Screen(SQLModel, table=True):
    """
    UI screen / page associated with a project.

    Generated by the UI/UX agent from features and use cases.
    ui_spec contains the design specification as structured JSON.
    """

    __tablename__ = "screen"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(foreign_key="project.id", index=True)
    screen_key: str = Field(max_length=100)
    name: str = Field(max_length=500)
    route: str | None = Field(default=None, max_length=500, description="URL route for this screen")
    description: str | None = Field(default=None)
    ui_spec: dict | None = Field(
        default=None,
        sa_column=Column(JSON),
        description="UI/UX specification generated by the design agent",
    )
    status: str = Field(default=ScreenStatus.PLANNED, max_length=30)
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )


# =============================================================================
# Technical Requirement
# =============================================================================


class TechnicalRequirement(SQLModel, table=True):
    """
    Technical-level requirement (infrastructure, performance, security, scalability).

    Generated by the ArchitectureAgent from product requirements.
    Distinct from product requirements — these are engineering constraints.
    """

    __tablename__ = "technical_requirement"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    project_id: uuid.UUID = Field(foreign_key="project.id", index=True)
    requirement_key: str = Field(max_length=100)
    title: str = Field(max_length=500)
    description: str = Field()
    category: str = Field(max_length=50, description="arch | security | perf | data | infra")
    priority: str = Field(default=RequirementPriority.MEDIUM, max_length=20)
    status: str = Field(default=RequirementStatus.DRAFT, max_length=30)
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, onupdate=func.now()),
    )
